name: centos 7

on:
  push:
    branches-ignore:
      - "web"
  pull_request:
    branches-ignore:
      - "web"

jobs:
  build_centos7:
    runs-on: [self-hosted, centos7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: halo
          submodules: true

      - name: Build
        run: |
          mkdir -p /tmp/centos.cache
          rm -fr ${{runner.workspace}}/$repo_name/output
          mkdir -p ${{runner.workspace}}/$repo_name/output
          docker pull $image_registry/computation/halo:$image_tag
          docker run --rm -v /tmp/centos.cache:/cache --tmpfs /build:exec --user=$UID:$GID \
            -v $poplar_sdk:/opt/poplar_sdk:ro \
            -v ${{runner.workspace}}/$repo_name:/host \
            $image_registry/computation/halo:$image_tag \
            /bin/bash -c 'source scl_source enable devtoolset-7 && cd /build && cmake -G Ninja /host/halo -DHALO_USE_TIDY_CHECK=OFF -DHALO_GEN_DOCS=OFF -DODLA_BUILD_POPART_USE_CXX11ABI=OFF -DODLA_BUILD_POPART_CUSTOM_OPS=ON -DODLA_BUILD_TRT=OFF -DODLA_BUILD_XNNPACK=OFF -DODLA_BUILD_EIGEN=OFF -DODLA_BUILD_DNNL=OFF -DHALO_BUILD_RTLIB=OFF -DHALO_USE_STATIC_PROTOBUF=ON ;ninja check-halo && ninja package && cp /build/*.bz2 /host/output'
        env:
          poplar_sdk: /opt/poplar_sdk-centos_7_6-2.1.0
          repo_name : heterogeneity-aware-lowering-and-optimization
          image_registry : registry-intl.us-west-1.aliyuncs.com
          image_tag : latest-devel-x86_64-centos7
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{runner.workspace}}/heterogeneity-aware-lowering-and-optimization/output/*.bz2
          if-no-files-found: error
