name: Publish Docker Images

on:
  push:
    branches:
      - "master"
  release:

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
  steps:
    - name: download
      uses: actions/download-artifact@v2
      with:
        name: artifact
